---
apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    app: demo
spec:
  containers:
    - name: demo-container
      image: gcr.io/k8s-k3s-418716/demo:v2.0.0
      ports:
        - containerPort: 8080
      readinessProbe:
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
      livenessProbe:
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
        httpGet:
          path: /
          port: http
      volumeMounts:
        - name: data
          mountPath: "/data"
  volumes:
    - name: data
      hostPath:
        path: /var/lib/app