---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container1
    image: nginx
    command: ['sh', '-c', 'echo "Hello World from container 1!" && sleep 3600']
  - name: nginx-container2
    image: nginx
    command: ['sh', '-c', 'echo "Hello World from container 2!" && sleep 3600']