---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: password
  restartPolicy: Never
  volumes:
  - name: redis-secret
    secret:
      secretName: redis-secret