---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  template:
    spec:
      containers:
        - name: google-sdk
          image: google/cloud-sdk:latest-alpine
          command: [ "/bin/sh", "-c", "tail -f /data/input/test.log" ]
          volumeMounts:
            - name: data-input
              mountPath: /data/storage
      restartPolicy: Never
      volumes:
        - name: data-input
          gcePersistentDisk:
            pdName: glow-data-disk-200
            fsType: ext4
      backoffLimit: 0